### ISSUE TITLE
Missing links for social profiles

### ISSUE THREAD

**Issue by amilajack** [flavianunes/flavianunes.github.io#1]
Hey! I came across your site and I really love it! When trying to find your GitHub I clicked on the GitHub icon and noticed that the [social icons don't have their corresponding URL's](https://github.com/flavianunes/flavianunes.github.io/blob/master/index.html#L140-L145). Awesome site by the way!

**Comment by flavianunes** [comment]
Hello! Thank you very much :smile: I'm working on it during my free time, that's why is incomplete, but I'm gonna fix it asap. Thanks
